# 補完機能
[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['denops.vim']
hook_source = '''
    call ddc#custom#patch_global('sources',['around'])
    call ddc#custom#patch_global('sourcesOptions',{
            '_': {
                    'matchers': ['matcher_head'],
                    'sorters': ['sorter_rank']
                },
            'around': {
                    'mark': 'around'
                },
            'nvim-lsp': {
                    'mark': 'lsp',
                    'forceCompletionPattern': '\.\w*|:\w*|->\w*'
                },
        })
    call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-nvim-lsp'
on_source = 'ddc.vim'

# Built-in LSP の補完をddc で利用する
# 言語サーバーのインストール状況の確認は:Mason
[[plugins]]
repo = 'neovim/nvim-lspconfig'
on_event = 'BufEnter'
hook_source = '''
lua << EOF
local mason = require('mason')
mason.setup({
        ui = {
                icons = {
                        package_installed = "v",
                        package_pending = ">",
                        package_uninstalled = "x"
                    }
            }
    })
local nvim_lsp = require('lspconfig')
local mason_lspconfig = require('mason-lspconfig')
mason_lspconfig.setup_handlers({ function(server_name)
    local opts = {}
    opts.on_attach = function(_, bufnr)
        local bufopts = { silent = true, buffer = bufnr }
        vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
        vim.keymap.set('n', 'gtD', vim.lsp.buf.type_definition, bufopts)
        vim.keymap.set('n', 'grf', vim.lsp.buf.references, bufopts)
        vim.keymap.set('n', '<space>p', vim.lsp.buf.format, bufopts)
    end
     nvim_lsp[server_name].setup(opts)
end })
EOF
'''
on_source = 'ddc.vim'

[[plugins]]
repo = 'williamboman/mason.nvim'
on_source = 'nvim-lspconfig'

[[plugins]]
repo = 'williamboman/mason-lspconfig.nvim'
on_source = 'nvim-lspconfig'
