# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# インデントの可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# コメント化
[[plugins]]
repo = 'tpope/vim-commentary'

# ツリー関連
# ディレクトリのツリー表示
[[plugins]]
repo = 'lambdalisue/fern.vim'
# vi . でファイラー起動
[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
# ツリーにアイコン表示
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
# ツリーのアイコンを色付け
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

# ステータスバーの表示
# [[plugins]]
# repo = 'vim-airline/vim-airline'
# [[plugins]]
# repo = 'vim-airline/vim-airline-themes'

# ステータスラインのアイコン
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# ステータスライン
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
lua << EOF
require('lualine').setup {
        options = {
                icons_enabled = true,
            }
    }
EOF
'''

# タブライン
[[plugins]]
repo = 'kdheepak/tabline.nvim'
hook_add = '''
lua << EOF
require('tabline').setup()
EOF
'''

# ステータスラインのアイコン
# [[plugins]]
# repo = 'ryanoasis/vim-devicons'

# テーマ
[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
    autocmd! VimEnter * nested colorscheme tokyonight-moon
'''

# 選択中のテキストをかっこなどでくくる
[[plugins]]
repo = 'tpope/vim-surround'

# マークダウンに関する設定
# マークダウンのプレビュー
[[plugins]]
repo = 'skanehira/preview-markdown.vim'
hook_add = '''
    let g:preview_markdown_auto_update = 1
    let g:preview_markdown_vertical = 1
'''
# マークダウンのテーブル作成
[[plugins]]
repo = 'mattn/vim-maketable'

# ターミナル
# [[plugins]]
# repo = 'Shougo/deol.nvim'
# hook_add = '''
#     nnoremap <silent><C-t> :<C-u>Dwol -split=floating<CR>
#     tnoremap <ESC>  <C-\><C-n>
# '''

# Deno関連
[[plugins]]
repo = 'vim-denops/denops.vim'

# lua 関連
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
