# プラグイン管理
[[plugins]]
repo = 'Shougo/dein.vim'

# インデントの可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# ツリー関連
# ディレクトリのツリー表示
[[plugins]]
repo = 'lambdalisue/fern.vim'
# vi . でファイラー起動
[[plugins]]
repo = 'lambdalisue/fern-hijack.vim'
# ツリーにアイコン表示
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
# ツリーのアイコンを色付け
[[plugins]]
repo = 'lambdalisue/glyph-palette.vim'

# ステータスラインのアイコン
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# ステータスライン
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = '''
lua << EOF
require('lualine').setup {
    options = {
            icons_enabled = true,
        }
    }
EOF
'''

# タブライン
[[plugins]]
repo = 'kdheepak/tabline.nvim'
hook_add = '''
lua << EOF
require('tabline').setup()
EOF
'''

# テーマ
[[plugins]]
repo = 'folke/tokyonight.nvim'
hook_add = '''
    autocmd! VimEnter * nested colorscheme tokyonight-moon
'''

# Deno 関連
[[plugins]]
repo = 'vim-denops/denops.vim'

# lua 関連
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
